name: rentease
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  blurhash: ^1.0.0
  cloud_firestore: ^4.4.3
  country_picker: 2.0.18
  email_validator: ^2.1.17
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  firebase_storage: ^11.0.15
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.7.0
  flutter_localization: ^0.1.12
  flutter_mobx: ^2.0.6+5
  flutter_otp_text_field: ^1.1.1
  flutter_provider: ^2.1.0
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  google_fonts: ^4.0.3
  google_sign_in: ^6.0.2
  image_picker: ^0.8.6
  intl: ^0.18.0
  mobx: ^2.1.4
  provider: ^6.0.0
  razorpay_flutter: 1.3.4

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.1.1

dependency_overrides:
  package_info_plus: any

flutter_icons:
  android: true
  image_path: "asset/images/launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
